include:
  - compose-deps.yaml

services:
  application:
    image: visage:latest
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - ./opt:/app/opt
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      maxmindmock:
        condition: service_healthy
