services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun start:dev
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
