create table analytics_event (
    id text primary key,
    website_id text not null references website (id),
    created text not null,
    duration_seconds integer,
    url_hostname text not null,
    url_path text not null,
    url_query_string text,
    referrer_hostname text,
    referrer_path text,
    referrer_query_string text,
    is_visitor integer not null,
    user_agent text not null,
    utm_source text,
    utm_medium text,
    utm_campaign text,
    utm_content text,
    window_screen_width integer not null,
    window_screen_height integer not null,
    window_viewport_width integer not null,
    window_viewport_height integer not null,
    device_os_name text,
    device_os_version text,
    device_browser_name text,
    device_browser_version text,
    locale_language text,
    locale_region text,
    geo_country_code text,
    geo_city_name text
);
