import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const $analyticsEvent = sqliteTable("analytics_event", {
  id: text().primaryKey(),
  created: text().notNull(),
  websiteId: text().notNull(),
  clientPageId: text(),
  durationSeconds: integer(),
  urlHostname: text().notNull(),
  urlPath: text().notNull(),
  urlQueryString: text(),
  referrerHostname: text(),
  referrerPath: text(),
  referrerQueryString: text(),
  isVisitor: integer({ mode: "boolean" }).notNull(),
  userAgent: text().notNull(),
  utmSource: text(),
  utmMedium: text(),
  utmCampaign: text(),
  utmContent: text(),
  windowScreenWidth: integer().notNull(),
  windowScreenHeight: integer().notNull(),
  windowViewportWidth: integer().notNull(),
  windowViewportHeight: integer().notNull(),
  deviceBrowserName: text(),
  deviceBrowserVersion: text(),
  deviceOsName: text(),
  deviceOsVersion: text(),
  localeLanguage: text(),
  localeRegion: text(),
  geoCountryCode: text(),
  geoCityName: text(),
});
